Consider the below code to answer further questions:
import numpy as np
list_ = ['1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)
Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [2]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [3]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [15]:
type(list_)

list

In [16]:
type(array_list)

numpy.ndarray

As we can see yes there is a difference in data type of both the varables.

Q2. Write a code to print the data type of each and every element of both the variables list_ and 
array_list.

In [18]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [19]:
for elements in array_list:
    print(type(elements))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and 
array_list? If so then print the data types of each and every element present in both the variables, list_ 
and array_list.

Consider the below code to answer further questions:

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

In [20]:
list_ = [ '1' , '2' , '3' , '4' , '5' ]

In [23]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [24]:
array_list = np.array(object = list_, dtype = int)

In [25]:
for elements in array_list:
    print(type(elements))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


As we can see Yes there is a difference in data types of the elements present in both the variables.

Q4. Write a code to find the following characteristics of variable, num_array:

(i)	 shape

(ii) size

In [26]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

np.shape(num_array)

(2, 3)

In [27]:
np.size(num_array)

6

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array 
creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [30]:
import numpy as shu

Matrix1 = shu.zeros([3,3])
print('\nMatrix 1:\n',Matrix1)


Matrix 1:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [31]:
import numpy as shubham

Matrix2 = shubham.identity(5)
print('\nMatrix 2:\n',Matrix2)


Matrix 2:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
